apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dai-huu/test.git' # Replace with your Git repository URL
    targetRevision: main
    path: infra/k8s
  destination:
    server: 'https://D9BA1369763C234F74DA3968D99911E1.gr7.ap-northeast-1.eks.amazonaws.com'
    namespace: ticketing-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-dev